name: storybook-docs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ğŸ§« Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron

      - name: ğŸ’¾ Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: ğŸ—ï¸ Install
        run: npm install

      - name: ğŸ“¦ Build Package
        run: npm run build

      - name: ğŸ¨ Build Storybook Docs
        run: npm run build:docs

      - name: â¬†ï¸ Upload Storybook
        uses: actions/upload-pages-artifact@v2
        with:
          path: storybook-static

      - name: ğŸš¢ Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ github.token }}
